"""Build fonts.css: the game's three OFL font families embedded as base64 woff2 (no external requests on portals).
Sources live in assets/fonts (licences: assets/fonts/OFL-*.txt), taken from github.com/google/fonts (ofl/...).
  OG Rubik  - Rubik Bold / Black / Black Italic, instanced from the variable font (UI, labels;
              bold italic captions)
  OG Hand   - Pangolin (comic speech bubbles)
  OG Logo   - Lilita One (logo / big numbers; Latin only - Turkish and Russian titles fall back to Rubik)
Every face is subset to Latin-1, Latin Extended-A (Polish, Turkish, Czech...), Cyrillic (Russian, Ukrainian) and the
symbols the game draws with text. Needs fontTools with brotli. Run: python tools/fonts.py"""
import base64, io, os
from fontTools.ttLib import TTFont
from fontTools import subset
from fontTools.varLib import instancer

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
F = lambda *p: os.path.join(ROOT, 'assets', 'fonts', *p)
TEXT = (''.join(chr(c) for c in range(0x20, 0x7f)) + ''.join(chr(c) for c in range(0xa0, 0x180)) +
        ''.join(chr(c) for c in range(0x400, 0x460)) + 'Ґґ' + '–—‘’“”„…•·×→←↑↓♪♥★☆✦°№')


def woff2_subset(font, text):
    opts = subset.Options(); opts.flavor = 'woff2'; opts.layout_features = ['kern', 'liga', 'calt', 'locl', 'mark', 'mkmk']
    opts.name_IDs = ['*']; opts.notdef_outline = True; opts.hinting = False; opts.desubroutinize = True
    s = subset.Subsetter(opts); s.populate(text=text); s.subset(font)
    b = io.BytesIO(); font.flavor = 'woff2'; font.save(b); return b.getvalue()


def face(family, data, weight=400, style='normal'):
    return "@font-face{font-family:'%s';src:url(data:font/woff2;base64,%s) format('woff2');font-weight:%s;font-style:%s;font-display:block}" % (family, base64.b64encode(data).decode(), weight, style)


css = ['/* generated by tools/fonts.py - OFL fonts (see assets/fonts/OFL-*.txt) */']
sizes = []
for wt, src, st in [(700, 'Rubik[wght].ttf', 'normal'), (900, 'Rubik[wght].ttf', 'normal'), (900, 'Rubik-Italic[wght].ttf', 'italic')]:
    static = instancer.instantiateVariableFont(TTFont(F(src)), {'wght': wt})
    data = woff2_subset(static, TEXT)
    sizes.append(len(data))
    css.append(face('OG Rubik', data, wt, st))
hand = woff2_subset(TTFont(F('Pangolin-Regular.ttf')), TEXT)
css.append(face('OG Hand', hand))
logo = woff2_subset(TTFont(F('LilitaOne-Regular.ttf')), TEXT)
css.append(face('OG Logo', logo))
open(os.path.join(ROOT, 'fonts.css'), 'w', encoding='utf-8', newline='\n').write('\n'.join(css) + '\n')
print('fonts.css', os.path.getsize(os.path.join(ROOT, 'fonts.css')), 'bytes; rubik', sizes, 'hand', len(hand), 'logo', len(logo))
